trainOpts = rlTrainingOptions(...
    'MaxEpisodes',5000,...
    'MaxStepsPerEpisode',floor(Tf/Ts),...
    'ScoreAveragingWindowLength',100,... 
    'Plots','training-progress',...
    'StopTrainingCriteria','AverageReward',...
    'StopTrainingValue',675,...
    'UseParallel',false);

doTraining = true;
if doTraining
    stats = train(agent,env,trainOpts);     
end
